<a href="https://colab.research.google.com/github/ArlesMolina/Proyecto/blob/main/Python_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# **Nombre: Arles Guevara Molina**
# **Matrícula:A01710380**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('netflix_titles.csv')

In [3]:
# El método `head` nos permite desplegar las primeras línea de un DataFrame.
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [4]:
def the_first():
    # Leer el archivo CSV
    df = pd.read_csv('netflix_titles.csv')

    # Retornar el primer renglón del DataFrame
    return df.head(0)

# Llamar la función
print(the_first())

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [5]:
def row_number():
    # Leer el archivo CSV
    df = pd.read_csv('netflix_titles.csv')

    # Retornar el número de registros (filas) del DataFrame
    return df.shape[0]

# Llamar la función
print(row_number())

7787

In [6]:
def released_year(year):
    # Leer el archivo CSV
    df = pd.read_csv('netflix_titles.csv')

    # Filtrar las filas donde 'release_year' es igual al año dado
    movies = df[df['release_year'] == year]

    # Retornar las películas filtradas
    return movies

# Año de consulta
year_query = 2020

# Llamar la función
print(released_year(year_query))

     show_id     type                                title           director  \
0         s1  TV Show                                   3%                NaN
24       s25  TV Show  ​SAINT SEIYA: Knights of the Zodiac                NaN
26       s27  TV Show                             (Un)Well                NaN
27       s28    Movie                               #Alive             Cho Il
29       s30  TV Show                             #blackAF                NaN
...      ...      ...                                  ...                ...
7725   s7726  TV Show                      You Cannot Hide                NaN
7734   s7735    Movie                      You've Got This  Salvador Espinosa
7738   s7739  TV Show                      Young Wallander                NaN
7741   s7742    Movie            Your Name Engraved Herein      Liu Kuang-hui
7744   s7745    Movie          Yours Sincerely, Kanan Gill       Neville Shah

                                                   cast         country  \
0     João Miguel, Bianca Comparato, Michel Gomes, R...          Brazil
24    Bryson Baugus, Emily Neves, Blake Shepard, Pat...           Japan
26                                                  NaN   United States
27                             Yoo Ah-in, Park Shin-hye     South Korea
29    Kenya Barris, Rashida Jones, Iman Benson, Genn...   United States
...                                                 ...             ...
7725  Blanca Soto, Eduardo Noriega, Iván Sánchez, Ma...          Mexico
7734  Mauricio Ochmann, Esmeralda Pimentel, Matteo G...          Mexico
7738  Adam Pålsson, Richard Dillane, Leanne Best, El...  United Kingdom
7741  Edward Chen, Tseng Ching-hua, Leon Dai, Jason ...          Taiwan
7744                                         Kanan Gill           India

             date_added  release_year rating   duration  \
0       August 14, 2020          2020  TV-MA  4 Seasons
24     January 23, 2020          2020  TV-14  2 Seasons
26      August 12, 2020          2020  TV-MA   1 Season
27    September 8, 2020          2020  TV-MA     99 min
29       April 17, 2020          2020  TV-MA   1 Season
...                 ...           ...    ...        ...
7725    October 1, 2020          2020  TV-MA   1 Season
7734    October 2, 2020          2020  TV-MA    112 min
7738  September 3, 2020          2020  TV-MA   1 Season
7741  December 23, 2020          2020  TV-MA    115 min
7744     April 24, 2020          2020  TV-MA     72 min

                                              listed_in  \
0     International TV Shows, TV Dramas, TV Sci-Fi &...
24                 Anime Series, International TV Shows
26                                           Reality TV
27       Horror Movies, International Movies, Thrillers
29                                          TV Comedies
...                                                 ...
7725  Crime TV Shows, International TV Shows, Spanis...
7734    Comedies, International Movies, Romantic Movies
7738  Crime TV Shows, International TV Shows, TV Dramas
7741         Dramas, International Movies, LGBTQ Movies
7744                                    Stand-Up Comedy

                                            description
0     In a future where the elite inhabit an island ...
24    Seiya and the Knights of the Zodiac rise again...
26    This docuseries takes a deep dive into the luc...
27    As a grisly virus rampages a city, a lone man ...
29    Kenya Barris and his family navigate relations...
...                                                 ...
7725  A nurse and her daughter flee her husband’s dr...
7734  An ad creative and a successful exec have a gr...
7738  An incendiary hate crime stirs civil unrest, f...
7741  In 1987, as martial law ends in Taiwan, Jia-ha...
7744  Revisiting life goals set in a letter written ...

[868 rows x 12 columns]

In [7]:
def origin_country(country):
    # Leer el archivo CSV
    df = pd.read_csv('netflix_titles.csv')

    # Filtrar las filas donde 'country' incluye el país dado
    movies = df[(df['country'].str.contains(country, na=False)) & (df['type'] == 'Movie')]

    # Retornar las películas filtradas
    return movies

# País de consulta
country_query = 'Mexico'

# Llamar la función
print(origin_country(country_query))

     show_id   type                   title  \
1         s2  Movie                    7:19
146     s147  Movie          A 3 Minute Hug
237     s238  Movie  A Tale of Two Kitchens
292     s293  Movie     Acapulco La vida va
328     s329  Movie          After the Raid
...      ...    ...                     ...
7404   s7405  Movie                Verónica
7482   s7483  Movie              Warehoused
7690   s7691  Movie       Y Tu Mamá También
7734   s7735  Movie         You've Got This
7773   s7774  Movie          Zoé: Panoramas

                                       director  \
1                             Jorge Michel Grau
146                           Everardo González
237                                 Trisha Ziff
292                    Alfonso Serrano Maturino
328                               Rodrigo Reyes
...                                         ...
7404  Carlos Algara, Alejandro Martinez-Beltran
7482                         Jack Zagha Kababie
7690                             Alfonso Cuarón
7734                          Salvador Espinosa
7773      Rodrigo Guardiola, Gabriel Cruz Rivas

                                                   cast  \
1     Demián Bichir, Héctor Bonilla, Oscar Serrano, ...
146                                                 NaN
237                                                 NaN
292   Patricio Castillo, Sergio Bustamante, Alejandr...
328                                                 NaN
...                                                 ...
7404          Arcelia Ramírez, Olga Segura, Sofía Garza
7482                    José Carlos Ruiz, Hoze Meléndez
7690  Maribel Verdú, Gael García Bernal, Diego Luna,...
7734  Mauricio Ochmann, Esmeralda Pimentel, Matteo G...
7773  Sergio Acosta, Jesús Báez, Ángel Mosqueda, Rod...

                    country         date_added  release_year rating duration  \
1                    Mexico  December 23, 2016          2016  TV-MA   93 min
146   Mexico, United States   October 28, 2019          2019  TV-PG   28 min
237   United States, Mexico       May 22, 2019          2019  TV-PG   30 min
292                  Mexico       June 3, 2017          2016  TV-MA   89 min
328   United States, Mexico  December 19, 2019          2019  TV-PG   25 min
...                     ...                ...           ...    ...      ...
7404                 Mexico    October 1, 2017          2017  TV-MA   81 min
7482                 Mexico   November 1, 2017          2015  TV-14   92 min
7690                 Mexico       June 1, 2017          2001      R  106 min
7734                 Mexico    October 2, 2020          2020  TV-MA  112 min
7773                 Mexico   November 1, 2019          2016  TV-MA   89 min

                                              listed_in  \
1                          Dramas, International Movies
146                 Documentaries, International Movies
237                 Documentaries, International Movies
292              Comedies, Dramas, International Movies
328                 Documentaries, International Movies
...                                                 ...
7404   Dramas, Independent Movies, International Movies
7482             Comedies, Dramas, International Movies
7690   Dramas, Independent Movies, International Movies
7734    Comedies, International Movies, Romantic Movies
7773  Documentaries, International Movies, Music & M...

                                            description
1     After a devastating earthquake hits Mexico Cit...
146   This documentary captures the joy and heartbre...
237   Mexico City restaurant star Gabriela Cámara op...
292   Three lifelong friends travel to Acapulco oste...
328   A large immigration raid in a small town leave...
...                                                 ...
7404  A reclusive psychologist agrees to treat a pat...
7482  A soon-to-be-retiring Mr. Lino teaches 20-some...
7690  When rich teens Tenoch and Julio meet the allu...
7734  An ad creative and a successful exec have a gr...
7773  This introspective rockumentary follows the ca...

[101 rows x 12 columns]

In [10]:
# Leer el archivo CSV
df = pd.read_csv('netflix_titles.csv')

# Crear un nuevo DataFrame con las columnas deseadas
new_df = df[['type', 'title', 'country', 'release_year']]

# Mostrar el nuevo DataFrame
print(new_df)

         type                                    title  \
0     TV Show                                       3%
1       Movie                                     7:19
2       Movie                                    23:59
3       Movie                                        9
4       Movie                                       21
...       ...                                      ...
7782    Movie                                     Zozo
7783    Movie                                   Zubaan
7784    Movie                        Zulu Man in Japan
7785  TV Show                    Zumbo's Just Desserts
7786    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS

                                                country  release_year
0                                                Brazil          2020
1                                                Mexico          2016
2                                             Singapore          2011
3                                         United States          2009
4                                         United States          2008
...                                                 ...           ...
7782  Sweden, Czech Republic, United Kingdom, Denmar...          2005
7783                                              India          2015
7784                                                NaN          2019
7785                                          Australia          2019
7786              United Kingdom, Canada, United States          2019

[7787 rows x 4 columns]

In [11]:
# Leer el archivo CSV
df = pd.read_csv('netflix_titles.csv')

# Agrupar por 'country' y 'type', y contar el número de producciones
productions_by_country = df.groupby(['country', 'type']).size().reset_index(name='count')

# Mostrar el resultado
print(productions_by_country)

                                               country     type  count
0                                            Argentina    Movie     34
1                                            Argentina  TV Show     16
2    Argentina, Brazil, France, Poland, Germany, De...    Movie      1
3                                     Argentina, Chile    Movie      1
4                               Argentina, Chile, Peru    Movie      1
..                                                 ...      ...    ...
768                                          Venezuela    Movie      1
769                                Venezuela, Colombia    Movie      1
770                                            Vietnam    Movie      5
771                                       West Germany    Movie      1
772                                           Zimbabwe    Movie      1

[773 rows x 3 columns]

In [12]:
def square_number(num):
    return num ** 2

# Ejemplo de uso
number = 5
print(square_number(number))

25